spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/lab?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  redis:
    host: localhost


common:
  ali-email-file: C:/data/lab/ali-email.properties

MYSQL_HOST: localhost
domain: http://localhost

lab:
  worker-id: 1
  data-center-id: 1
server:
  port: 8080
  servlet:
    context-path: /system
logging:
  level:
    com.lab: debug

---
spring:
  profiles: prod

common:
  ali-email-file: /lab/conf/ali-email.properties